name: Release Terraform Provider

on:
  push:
    tags:
      - 'v*'  # Se dispara solo en tags que empiecen por "v"

permissions:
  contents: write  # Necesario para crear releases y subir assets

jobs:
  build:
    name: Build Provider Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build provider
        run: |
          mkdir -p bin
          EXT=""
          [[ "${{ matrix.goos }}" == "windows" ]] && EXT=".exe"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o bin/terraform-provider-googleworkspace_${{ matrix.goos }}_${{ matrix.goarch }}${EXT}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: terraform-provider-googleworkspace-${{ matrix.goos }}-${{ matrix.goarch }}
          path: bin/*

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: bin

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
